import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppProvider } from "./providers/app-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dictionary App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={inter.className + "flex min-h-svh flex-col"}
        suppressHydrationWarning
      >
        <AppProvider>
          <main className="flex flex-1 flex-col">{children}</main>
        </AppProvider>
      </body>
    </html>
  );
}
